tinyhttp/tinyhttp

examples/dev-server/main.js
examples/dev-server/package.json
examples/dev-server/server.js

Updating the dev-server example so that it:
- Reloads the server on changes
- Reloads the client
- Shows server errors on the client
P.S. i am not entirely sure whats the advertised use case with this example, but `serve-handler` seems to be a very "strict" static server middleware - it directly outputs a 404 if it fails to find a file for any request - instead of giving other middlewares the chance to do something better :D, so this makes it imho hard to use along with tinyhttp.

refactor: update dev-server example

---

examples/http2/README.md
examples/http2/index.js
examples/http2/package.json

I've added http/2 example. To get this up and running, you'll need to generate the certificate and key. Simply run
```
openssl req -x509 -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' \
-keyout localhost-privkey.pem -out localhost-cert.pem
```
then run it using `node index.js`.
Test this using `curl https://localhos:3000 -kiv`. You should see that the connection is using HTTP/2 instead of HTTP/1.1

added http/2 example

---

examples/https/README.md
examples/https/index.js
examples/https/package.json

I've added the https example for tinyhttp ( see #21 for more examples ). To set this up, you'll need to generate the certificate and key for this example, run:
```sh
openssl req -x509 -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' \
-keyout localhost-privkey.pem -out localhost-cert.pem
```
Install the dependencies using `pnpm install`, then run the app using `node index.js`. Test it using `curl https://localhost:3000/ -k`. What you should get is `Hello from https server!`

added https example

---

__tests__/request.test.ts
packages/app/src/extend.ts
packages/app/src/request.ts
packages/app/src/utils/request.ts

implement `req.ip` and `req.ips` . The implementation is a bit different from `express`.
- There was already an address `trust` function implemented in our codebase. and Both of these methods rely on that for making sure that the incoming address is trustworthy.
- `req.ips` returns all the `IP addresses` when the request is coming under a proxy. And when it there is no proxy it just returns the first [untrusted IP](https://www.npmjs.com/package/proxy-addr#proxyaddrallreq-trust) which is `127.0.0.1` in the local server
- `req.ip` method has a regex replacer in its return statement which removes the prefix added by the [OS to `IPv4` to convert it to `IPv6`](https://stackoverflow.com/a/35560645/9360234). Basically it just prefixes `:ffff:` in front of the IPv4. So that regex replacer removes …

:sparkles: implement req.ip and req.ips

---

packages/app/CHANGELOG.md
packages/app/package.json
packages/app/src/app.ts
packages/bot-detector/CHANGELOG.md
packages/bot-detector/package.json
packages/cookie-parser/CHANGELOG.md
packages/cookie-parser/package.json
packages/ip-filter/CHANGELOG.md
packages/ip-filter/package.json
packages/logger/CHANGELOG.md
packages/logger/package.json
packages/markdown/CHANGELOG.md
packages/markdown/package.json
packages/pug/CHANGELOG.md
packages/pug/package.json

Tinyhttp used to default to localhost when it came to bind an address, which is incompatible with 99% of serverless services (like Heroku), but now it defaults to 0.0.0.0
Fixes #85

fix: changed the default binding address from localhost to 0.0.0.0

---

__tests__/modules/accepts.test.ts

- types unit test for checking that it returns the first option when there's no header
- uncommented accept.types() tests

Unit testing: uncommented accepts tests and added another one

---

packages/accepts/src/index.ts

- if types was undefined it couldn't reach the step where it returned all the options, because it stopped with an error before that

fix: added a check to see if types is undefined

---

examples/jwt/README.md
examples/session/README.md
examples/session/index.js
examples/session/package.json

Implements #103 
Adding an example of an auth (session) using tinyhttp and [@tinyhttp/session](https://tinyhttp.v1rtl.site/mw/session)

#103: Add session example

---

__tests__/wares/bot-detector.test.ts

Implements #111 
Adding tests for the bot-detector middleware

Add unit test for bot-detector middleware

---

__tests__/modules/req.test.ts
packages/type-is/package.json
packages/type-is/src/index.ts

To fix #150 I've replaced media-typer with another module from the same library (jshttp) that is more appropriate to parse a content type header (as stated in media-typer readme https://github.com/jshttp/media-typer#media-typer)

reqIs does not correctly parse the Content-Type header #150

---

__tests__/wares/session.test.ts
packages/session/src/index.ts

- and the rest of `session` properties :D

Tests for session.save, session.touch, session.destroy

---

__tests__/modules/type-is.test.ts

Now almost all lines in `type-is` module are covered by tests

test: add tests for type-is module

---

packages/router/src/index.ts

It seems like tinyhttp is incompatible with Express' NextFunction, making types for middleware that was originally designed for Express invalid. If this is intentional or if I'm wrong, feel free to just close this PR 😸

Remove undefined from NextFunction

---

__tests__/wares/cors.test.ts
packages/cors/README.md
packages/cors/package.json
packages/cors/src/index.ts

fix!: preflightContinue defaults to false again now
fix: added preflight just for options method (as per express' cors)
chore: bump version
I've put a sample repo with this version on https://github.com/aldy505/tinyhttp-cors-test

fix: #229 - CORS response on preflight

---

packages/cors/src/index.ts

closes https://github.com/talentlessguy/tinyhttp/issues/256

feat(cors): set default allowed headers to content-type

---

packages/cli/src/utils.ts

Fixes #259
Hi @talentlessguy, how does this look?
Let me know if this needs any changes.
Thanks

TypeError: Cannot convert undefined or null to object for projects without dev dependencies in CLI

---

__tests__/modules/cli.test.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts

Adds: #263
Hey @talentlessguy, does this look good? 
I can make changes if needed, thank you :)

CLI: use the project name as name in package.json

---

packages/app/src/app.ts
tests/core/app.test.ts

This PR aims to solve the issue described in #278.
Solution handles the problematic test case as it would be expected, and doesn't break the existing ones.
(The project, as well as some technologies used were new to me, so if I did any mistakes please point them out, and I'd be glad to fix them.)
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#278: Some router paths don't work if router is mounted after defining routes](https://issuehunt.io/repos/271918885/issues/278)
---
</details>

Fix router mount order (fixes #278)

---

COMPARISON.md

The benchmarks link is 404. I entered a link to the Web Frameworks Benchmark site comparing the three.

Fix broken benchmarks link

---

.changeset/clever-camels-relate.md
packages/app/package.json
packages/app/src/app.ts
tests/core/app.test.ts

Also modified tests to check req.params
Closes #314

fix(core): pass req.params to next handler

---

packages/url/src/index.ts
tests/modules/url.test.ts

closes #330 
returns empty object ('{}') if no query params found

Fix: Issue #330 empty query params

---

packages/url/src/index.ts
tests/modules/url.test.ts

When optional URL params (i.e. `/foo/:bar?`) are not supplied in the request, the corresponding key should also not be present in the `getURLParams` result.
Closes #331

fix: omit optional URL params when not supplied in request

---

packages/accepts/README.md
packages/accepts/package.json
packages/content-disposition/README.md
packages/content-disposition/package.json
packages/encode-url/README.md
packages/encode-url/package.json
packages/forwarded/README.md
packages/proxy-addr/README.md
packages/type-is/README.md

Fixes #343
---
I did do a global search and replace here, as the same text was used consistently in `package.json` and `README.md`. I left the reference to CommonJS in the main readme, I simply don't know whether or not tinyhttp supports _consuming_ CommonJS modules. :)

docs: remove CommonJS references

---

packages/cookie-signature/src/index.ts

`unsign` never returns `true`, so make the return type `string | false` instead. This change allows type-narrowing code like this to work correctly.
```js
const redirectUri = unsign(state, env.COOKIE_SECRET);
if (redirectUri === false) {
throw new Error('Invalid OAuth state');
}
```

Fix cookie-signature unsign return type

---

packages/res/src/redirect.ts
tests/modules/res.test.ts

This PR attempts to resolve issue #345 in the **res** package
The server responds with a 406 (Not Acceptable) error when the client requests an unsupported MIME-type
A valid response with an empty body is sent to the client
Fixes #345

Send valid response when requested MIME type is unsupported

---

packages/send/src/sendFile.ts
tests/modules/send.test.ts

This PR aims to resolve [Issue#360](https://github.com/tinyhttp/tinyhttp/issues/360).
In sendFile.ts, I added a check to see if the "Content-Type" header had been previously set, and it will only pull the MIME type from the file if the header has not been set.
I then added an extra test inside send.test.ts, where it sets the "Content-Type" header to text/markdown for a text/plain file, to see if it persists. 
Please let me know if any advice/ changes required. 
Thanks!

fix: prevent res.sendFile() from overwriting 'Content-Type' header if previously set

---

packages/app/src/response.ts

Closes #370 by adding a new type variable to the Response interface and passing the same type arguments to the Response object returned from every method of the Response interface

fix: make Response body generic

---

packages/accepts/LICENSE
packages/accepts/package.json
packages/app/package.json
packages/content-disposition/LICENSE
packages/content-disposition/package.json
packages/cookie-signature/LICENSE
packages/cookie/LICENSE
packages/dotenv/LICENSE
packages/encode-url/LICENSE
packages/etag/LICENSE
packages/forwarded/LICENSE
packages/jsonp/LICENSE
packages/proxy-addr/LICENSE
packages/rate-limit/LICENSE
packages/req/LICENSE
packages/router/LICENSE
packages/type-is/LICENSE
packages/url/LICENSE

Hi Team,
Could you please approve my very simple PR?
I want to make sure that none of the tinyhttp packages ever come up as "license-none" during open source scanning. 
Please approve if you are happy with it :)

Adding Missing MIT license in packages to ensure open source scanning does not pick this up as "License-None" CVE

---

packages/app/src/app.ts

* App.locals should be `Record<string any>` because the app doesn't really care about the values, it just pass them to functions. They can even be `<string, unknown>`.
* Callback for template rendering function should be `(error: Error | null, html: unknown) => void` because error can be null.

Correct type declaration

---

packages/app/src/app.ts
tests/core/request.test.ts

As stated [before](https://github.com/tinyhttp/tinyhttp/pull/352#issue-1181241448), ipv6 fails on github actions. The tests are skipped by checking for default environment variables that action uses. Also, closes #351

fix: skip ipv6 tests only for github cicd #351

---

packages/app/src/app.ts
packages/router/src/index.ts
tests/core/app.test.ts

`app.path()` would default to `//` when mounted for array of paths. This fixes it and uses express style mounting.
fixes #389

subapps return the path correctly when mounted on array of paths

---

packages/res/src/redirect.ts
packages/res/src/util.ts
tests/modules/etag.test.ts
tests/modules/res.test.ts

Passes all the tests unlike es-escape-html and is one less dependency on `@tinyhttp/res`

feat(res): remove dependency on escapeHTML and inline it
