tinyhttp/tinyhttp

packages/cors/README.md
packages/cors/package.json
packages/cors/src/index.ts
pnpm-lock.yaml

Complete rewrite of the middleware, also rewrote the documentation

Complete rewrite of the cors middleware

---

packages/cors/package.json

Fixed version to publish it on npm

Fixed cors version

---

examples/mongodb/index.js
examples/mongodb/package.json

I've finished the example for mongodb. To set this up, all you have to do is add `DB_URI` on `.env` file and you're good to go.
It has 4 methods which are `GET`, `POST`, `DELETE`, and `PUT`. It uses `req.query` instead of `req.body` so make sure to not get it wrong.
`GET /notes` will return a list of notes with 2 properties which are title and desc.
`POST /notes` requires you to enter 2 query which are title and desc.  
`DELETE /notes` only need an ID of that note.
`PUT /notes` requires and ID of the item that you want to update, as well as title and desc for the updated one.

finished mongodb example

---

packages/app/src/router.ts

I've added the rest of http methods listed from `http.METHODS` according to #24. There's around 26 of them if I did the math correctly.

added all of http methods

---

__tests__/router.test.ts

I've added some http method test in continuation of #24. Some of them are `GET`, `POST`, `PUT`, `DELETE`, etc.

added some route tests

---

.huskyrc.json
package.json

I separated the lint script and added it to the `pre-commit` hook along with the test script. I was not sure about adding the lint script to the GitHub actions so didn't add but if you want to add it there I will just add it there too.
@talentlessguy

Setup husky with pre commit hook

---

CONTRIBUTING.md

it seems, @talentlessguy have added the pre commit hook, so i just removed the line in [CONTRIBUTING](https://github.com/talentlessguy/tinyhttp/blob/master/CONTRIBUTING.md) which mention to add pre-commit hook

remove todo

---

__tests__/wares/jwt.test.ts

- Added malformed input test
- Fixed a bug that made all the tests pass without properly checking

JWT testing

---

__tests__/modules/accepts.test.ts

NEW:
- added accepts.language() testing
- - added testing with arguments
- - added testing without arguments
---
FIX:
- modified the createRequest function

Wrote more tests for the accepts package

---

__tests__/modules/accepts.test.ts

- multiple tests for different sections of the code
- reached 100% coverage

test: added multiple tests for the accepts package

---

__tests__/modules/cookie.test.ts
packages/cookie/src/index.ts

- multiple unit tests both for parsing and serializing
- deleted unreachable default arguments
_Correlated issue:_ #92

Tests: Complete coverage on the cookie module

---

examples/react-ssr/README.md
examples/react-ssr/app.js
examples/react-ssr/index.js
examples/react-ssr/package.json

Resolve #109 
I don't used `react-ssr` and tried to create an example similar to the other ones present in the repository. Let me know if you need something different :)

Add tinyhttp + react example

---

__tests__/modules/jsonp.test.ts

Implements #123 
Line number 23 looks unreachable and hence is left out from the coverage.

Adding unit test for jsonp middleware

---

__tests__/modules/etag.test.ts

Added tests for ETag

---

__tests__/modules/send.test.ts
packages/send/src/sendFile.ts

Chore - Send tests

---

__tests__/wares/cors.test.ts

added test for cors package with origin function

---

examples/caddy/Caddyfile
examples/caddy/README.md
examples/caddy/package.json
examples/caddy/server.js

Added example for caddy

---

packages/bot-detector/src/index.ts

Make isBot and botName lazy and idempotent:
- Will only calculate when requested
- Will only calculate once per request

lazy isbot

---

examples/aws/README.md
examples/aws/index.js
examples/aws/package.json

Add an AWS example with links to tutorials how to do it with Express + example code for tinyhttp

Add AWS example

---

packages/bot-detector/README.md

- Fix isbot link
- Specify that bot-detector getters are lazy

[Docs] bot-detector package

---

site/pages/md/learn.md

Documentation variable name fix

Documentation : fix callback variable name

---

__tests__/wares/cors.test.ts
packages/cors/README.md
packages/cors/package.json
packages/cors/src/index.ts

regarding #224 
see [this repo](https://github.com/aldy505/tinyhttp-cors-test) for sample test and usage

feat(cors): support for multiple origin using array and regex

---

site/static/index.html

Home page mentioned 4 of 6 dependencies are of tinyhttp's but when I looked at the dependencies on npm I see 5 of them are of tinyhttp's. This tiny PR is to fix that

Fix dependency count

---

__tests__/modules/send.test.ts
packages/send/src/send.ts

Before it didn't send anything except headers and didn't close a connection.

fix: res.send(buffer)

---

__tests__/core/app.test.ts
packages/app/src/app.ts
packages/router/src/index.ts

---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#238: Unable to set url prefix for the application](https://issuehunt.io/repos/271918885/issues/238)
---
</details>

fix: Unable to set url prefix for the application

---

examples/couchdb/README.md

chore: fix typo in couchdb/README.md

---

examples/neo4j/README.md
examples/neo4j/docker-compose.yml
examples/neo4j/index.js
examples/neo4j/package.json

I'm working on a project that needs the neo4j so I choose tinyhttp because it's funny and powerful, therefore I create an example for it :)

example: add neo4j example

---

packages/app/src/request.ts

chore: replace req.connection with req.socket

---

packages/app/src/app.ts
packages/app/src/onError.ts
tests/core/app.test.ts

feat: Allow parent error handlers to handle for sub apps

---

packages/res/src/index.ts

Required for  modern node usage.

Fix missing file extension

---

tsconfig.json

I have added the following options
1. `"declarationMap": true` - helps map back to the original files https://www.typescriptlang.org/tsconfig#declarationMap
2. `"composite": true` - uses previous build files to speed up building process https://www.typescriptlang.org/tsconfig#composite
3. `"sourceMap": true` - Generates source maps https://www.typescriptlang.org/tsconfig#sourceMap
4. `"alwaysStrict": true` - Uses strict mode. https://www.typescriptlang.org/tsconfig#alwaysStrict
Other options are welcome.

Added more options in tsconfig

---

.github/workflows/main.yml

In the last PR, coverage would send 3 reports although the build was the same. This changes will send coverage report only if os is ubuntu-latest. I also reduced the code by using build matrix.

used matrix to remove duplicate code and made coverage conditional

---

packages/req/src/index.ts
pnpm-lock.yaml
tests/modules/req.test.ts

fix: closes #406

---

packages/app/src/app.ts
packages/app/src/request.ts
pnpm-lock.yaml
tests/core/app.test.ts

req.route is assigned the correct middleware if multiple are present 

---

packages/app/src/app.ts
tests/core/request.test.ts

fix: correctly update req.url on routes and mws

---

packages/app/package.json
packages/app/src/app.ts
packages/app/src/types.ts
packages/jsonp/package.json
packages/router/src/index.ts
tests/core/request.test.ts

Added application interface for correct typing of req/res parameters of subapp callbacks.

feat: App interface

---

.changeset/early-apes-serve.md
.github/workflows/main.yml
.github/workflows/release.yml
packages/app/src/extend.ts
packages/app/src/request.ts

it was missing from the app, oops

Fix req is

---

.changeset/salty-pumas-search.md
biome.json
packages/app/src/app.ts
packages/app/src/extend.ts
packages/app/src/request.ts
packages/app/src/types.ts
packages/app/src/view.ts
packages/forwarded/src/index.ts
packages/ip-filter/src/index.ts
packages/rate-limit/src/rate-limit.ts
packages/req/src/index.ts
packages/res/src/headers.ts
tests/modules/dotenv.test.ts
tests/modules/etag.test.ts
tests/modules/req.test.ts
tests/modules/res.test.ts
tests/modules/router.test.ts

* stop using non-null assertion
* make `View` class throw instead of `res.render`, when no view file is found

Slight refactor
